# Generated by Django 3.2.8 on 2021-10-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
